### ISSUE TITLE
Could not connect, Bridge service stopped

### ISSUE THREAD

**Issue by Midifreakz** [Kakise/homebridge-tuya-door-cloud#4]
Hi, first, thank you so much for putting work into this plugin! 

Unfortunately I'm getting the following error, do you have any idea what might be happening? 
I have a snippet of my config file here: https://pastebin.com/Zpe8HgpV

[DoorSensorPlatform] [ { display_name: 'SENSOR 1', device_id: 'xxxxxxxxxxxxxx' } ]
30/07/2021, 12:21:20 [DoorSensorPlatform] Adding new accessory: SENSOR 1
30/07/2021, 12:21:20 TypeError: this.service.getCharacteristic(...).onGet is not a function
    at new TuyaDoor (/home/hoobs/.hoobs/node_modules/homebridge-tuya-door-cloud/dist/platformAccessory.js:26:14)
    at TuyaDoorPlatform.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-tuya-door-cloud/dist/platform.js:88:17)
    at HomebridgeAPI.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-tuya-door-cloud/dist/platform.js:32:18)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:81:14)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:160:18)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
30/07/2021, 12:21:20 (node:7045) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND openapi.tuyaeurope.com
30/07/2021, 12:21:20 at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
30/07/2021, 12:21:20 (Use `node --trace-warnings ...` to show where the warning was created)
30/07/2021, 12:21:20 (node:7045) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
30/07/2021, 12:21:20 (node:7045) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
30/07/2021, 12:21:20 Got SIGTERM, shutting down Bridge...

**Comment by Kakise** [comment]
Hello, this is a dedup of #3 a hot fix is being worked on and will be merged ASAP
